# Generated by Django 3.2.19 on 2023-05-28 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jenji', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='email',
        ),
    ]
