# Generated by Django 3.2.19 on 2023-05-28 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jenji', '0003_auto_20230528_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='day',
            new_name='date',
        ),
    ]
